# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: Hadia <Hadia@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/11/04 15:56:12 by mregnaut          #+#    #+#              #
#    Updated: 2025/07/10 19:23:46 by Hadia            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

CFLAGS = -Wall \
		 -Werror \
		 -Wextra
		 
CC = cc
ARFLAGS = rcs
AR = ar

FILES = ft_bzero.c \
		ft_isalnum.c \
		ft_isalpha.c \
		ft_isascii.c \
		ft_isspace.c \
		ft_isdigit.c \
		ft_isprint.c \
		ft_memchr.c \
		ft_memcmp.c \
		ft_memcpy.c \
		ft_memset.c \
		ft_strchr.c \
		ft_strlen.c \
		ft_strrchr.c \
		ft_tolower.c \
		ft_toupper.c \
		ft_atoi.c \
		ft_calloc.c \
		ft_strdup.c \
		ft_strndup.c \
		ft_memmove.c \
		ft_putchar_fd.c \
		ft_putendl_fd.c \
		ft_putnbr_fd.c \
		ft_putstr_fd.c \
		ft_strjoin.c \
		ft_strlcat.c \
		ft_strlcpy.c \
		ft_strncmp.c \
		ft_strcmp.c \
		ft_strnstr.c \
		ft_strtrim.c \
		ft_substr.c \
		ft_itoa.c \
		ft_strmapi.c \
		ft_striteri.c \
		ft_split.c \
		get_next_line.c \
		gnl_utils.c

BONUS =	ft_lstnew_bonus.c \
		ft_lstadd_front_bonus.c \
		ft_lstsize_bonus.c \
		ft_lstlast_bonus.c \
		ft_lstadd_back_bonus.c \
		ft_lstdelone_bonus.c \
		ft_lstclear_bonus.c \
		ft_lstiter_bonus.c \
		ft_lstmap_bonus.c

OBJECTS = $(FILES:.c=.o)

BONUS_OBJECTS = $(BONUS:.c=.o)

HEADERS = libft.h

.PHONY: all
all: $(NAME)

$(NAME): $(OBJECTS) $(HEADERS)
	$(AR) $(ARFLAGS) $@ $(OBJECTS)

.PHONY: clean
clean:
	rm -rf $(OBJECTS) $(BONUS_OBJECTS)

.PHONY: fclean
fclean: clean
	rm -rf $(NAME)

.PHONY: re
re: fclean all

.PHONY: bonus
bonus: $(HEADERS)
	$(MAKE) $(NAME) FILES="$(FILES) $(BONUS)"